module.exports = [
  // {
  //   "id": "Qbax5Oy7L8WKf74l",
  //   "name": "Buku A",
  //   "year": 2010,
  //   "author": "John Doe",
  //   "summary": "Lorem ipsum dolor sit amet",
  //   "publisher": "Dicoding Indonesia",
  //   "pageCount": 100,
  //   "readPage": 25,
  //   "finished": false,
  //   "reading": false,
  //   "insertedAt": "2021-03-04T09:11:44.598Z",
  //   "updatedAt": "2021-03-04T09:11:44.598Z"
  // },
  // {
  //   "id": "xKwePbGncpVQkYq3",
  //   "name": "Buku B",
  //   "year": 2015,
  //   "author": "Jane Smith",
  //   "summary": "Consectetur adipiscing elit",
  //   "publisher": "Gramedia",
  //   "pageCount": 150,
  //   "readPage": 100,
  //   "finished": true,
  //   "reading": false,
  //   "insertedAt": "2021-03-05T11:22:33.789Z",
  //   "updatedAt": "2021-03-05T11:22:33.789Z"
  // },
  // {
  //   "id": "vYzTAs0cXUg0UJk7",
  //   "name": "Buku C",
  //   "year": 2018,
  //   "author": "Alice Johnson",
  //   "summary": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
  //   "publisher": "Penerbit Terang",
  //   "pageCount": 200,
  //   "readPage": 50,
  //   "finished": false,
  //   "reading": true,
  //   "insertedAt": "2021-03-06T13:45:22.123Z",
  //   "updatedAt": "2021-03-06T13:45:22.123Z"
  // },
  // {
  //   "id": "mQxeWrzHgDplGj69",
  //   "name": "Buku D",
  //   "year": 2020,
  //   "author": "David Brown",
  //   "summary": "Ut enim ad minim veniam",
  //   "publisher": "Elex Media Komputindo",
  //   "pageCount": 120,
  //   "readPage": 90,
  //   "finished": true,
  //   "reading": false,
  //   "insertedAt": "2021-03-07T15:54:11.456Z",
  //   "updatedAt": "2021-03-07T15:54:11.456Z"
  // },
  // {
  //   "id": "qRtyGhJkLmNzPoi3",
  //   "name": "Buku E",
  //   "year": 2012,
  //   "author": "Michael Lee",
  //   "summary": "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
  //   "publisher": "Bentang Pustaka",
  //   "pageCount": 180,
  //   "readPage": 60,
  //   "finished": false,
  //   "reading": true,
  //   "insertedAt": "2021-03-08T17:33:44.567Z",
  //   "updatedAt": "2021-03-08T17:33:44.567Z"
  // },
  // {
  //   "id": "zXcvBnMkLpQwEr4",
  //   "name": "Buku F",
  //   "year": 2019,
  //   "author": "Emma Taylor",
  //   "summary": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
  //   "publisher": "Bhuana Ilmu Populer",
  //   "pageCount": 250,
  //   "readPage": 200,
  //   "finished": true,
  //   "reading": false,
  //   "insertedAt": "2021-03-09T09:01:33.987Z",
  //   "updatedAt": "2021-03-09T09:01:33.987Z"
  // },
  // {
  //   "id": "aSdfGhJkLqWeRt5",
  //   "name": "Buku G",
  //   "year": 2017,
  //   "author": "Sophia Clark",
  //   "summary": "Excepteur sint occaecat cupidatat non proident",
  //   "publisher": "Bentang Pustaka",
  //   "pageCount": 300,
  //   "readPage": 150,
  //   "finished": false,
  //   "reading": true,
  //   "insertedAt": "2021-03-10T12:45:56.321Z",
  //   "updatedAt": "2021-03-10T12:45:56.321Z"
  // },
  // {
  //   "id": "zMxcVbNlMwQpOe2",
  //   "name": "Buku H",
  //   "year": 2016,
  //   "author": "Christopher Brown",
  //   "summary": "Sunt in culpa qui officia deserunt mollit anim id est laborum",
  //   "publisher": "Penerbit Terang",
  //   "pageCount": 220,
  //   "readPage": 50,
  //   "finished": false,
  //   "reading": true,
  //   "insertedAt": "2021-03-11T14:32:45.789Z",
  //   "updatedAt": "2021-03-11T14:32:45.789Z"
  // },
  // {
  //   "id": "qAzXsWcEdVfRtGb1",
  //   "name": "Buku I",
  //   "year": 2014,
  //   "author": "Olivia Johnson",
  //   "summary": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
  //   "publisher": "Gramedia",
  //   "pageCount": 190,
  //   "readPage": 100,
  //   "finished": true,
  //   "reading": false,
  //   "insertedAt": "2021-03-12T16:23:55.123Z",
  //   "updatedAt": "2021-03-12T16:23:55.123Z"
  // },
  // {
  //   "id": "wSxErCfVdGbQaZp9",
  //   "name": "Buku J",
  //   "year": 2021,
  //   "author": "Daniel Smith",
  //   "summary": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
  //   "publisher": "Elex Media Komputindo",
  //   "pageCount": 280,
  //   "readPage": 120,
  //   "finished": false,
  //   "reading": true,
  //   "insertedAt": "2021-03-13T18:45:33.456Z",
  //   "updatedAt": "2021-03-13T18:45:33.456Z"
  // },
  // {
  //   "id": "kYujHbGtFrDcVbN0",
  //   "name": "Buku K",
  //   "year": 2013,
  //   "author": "Jessica White",
  //   "summary": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
  //   "publisher": "Penerbit Terang",
  //   "pageCount": 170,
  //   "readPage": 70,
  //   "finished": false,
  //   "reading": true,
  //   "insertedAt": "2021-03-14T20:54:44.789Z",
  //   "updatedAt": "2021-03-14T20:54:44.789Z"
  // }
]